Complementary Set Library: cset::space Class Reference
cset::space Class Reference
Abstract multi-dimensional integer space.
#include <space.h>
Public Member Functions
space (dim_t dim) noexcept
Construct an integer space of dimension dim.
space (const space &other) noexcept
Copy constructor.
space (space &&other) noexcept
Move constructor.
void swap (space &other) noexcept
Non-throwing Swap.
space & operator= (space other) noexcept
Copy assignment operator.
space operator* (const space &other) const
Construct a Cartesian product space.
bool operator== (const space &other) const
Equality operator.
bool operator!= (const space &other) const
Inequality operator.
void print (std::ostream &out) const
Feeds a representation of a space to an output stream.
Detailed Description
Abstract multi-dimensional integer space.
This class represents an infinite multi-dimensional integer space of finite dimension. It is used as the underlying structure above which inset and outset are build.
Definition at line 28 of file space.h.
Constructor & Destructor Documentation
cset::space::space (dim_t dim) inline noexcept
Construct an integer space of dimension dim.
Parameters
dim Dimension of the constructed space.
Definition at line 34 of file space.h.
Referenced by operator*().
cset::space::space (const space & other) inline noexcept
Copy constructor.
Parameters
other Copied space.
Definition at line 40 of file space.h.
cset::space::space (space && other) inline noexcept
Move constructor.
Parameters
other Consumed space.
Definition at line 46 of file space.h.
Member Function Documentation
bool cset::space::operator!= (const space & other) const inline
Inequality operator.
Parameters
other Space to compare against.
Return values
true if arguments are of different dimension.
false otherwise.
Definition at line 90 of file space.h.
space cset::space::operator* (const space & other) const inline
Construct a Cartesian product space.
Parameters
other Space against which to do a Cartesian product.
Returns
A space of dimension the sum of that of the arguments.
Definition at line 70 of file space.h.
References space().
space& cset::space::operator= (space other) inline noexcept
Copy assignment operator.
Parameters
other Original space.
Returns
Reference to this space.
Definition at line 59 of file space.h.
References swap().
bool cset::space::operator== (const space & other) const inline
Equality operator.
Parameters
other Space to compare against.
Return values
true if arguments are of the same dimension.
false otherwise.
Definition at line 80 of file space.h.
void cset::space::print (std::ostream & out) const
Feeds a representation of a space to an output stream.
Parameters
out Stream in which to print.
Definition at line 13 of file space.cpp.
Referenced by operator<<().
The documentation for this class was generated from the following files:
include/cset/space.h
src/space.cpp